# Update Checker Settings
update-checker:
  enable: true
  console: true # Post message to console
  op: true # Send update notification to opped players on join

# Language, specify the language file to use, for example `en_US` which will load `/lang/en_US.json`
language: "en_US"

# Enabled or disable specific modules
module:
  tag:
    enabled: true
  namecolor:
    enabled: true
  nickname:
    enabled: true
    prefix:
      enabled: true
      string: ""
    set-displayname: true # Sets the displayname to the nickname. Disable this if you have another plugin which modifies the displayname
    set-listname: true # Sets the listname (shown in the tab-menu) for the player. Disable this if you have another plugin which modifies the listname
    length: 20 # The maximum allowed length for nicknames. Allowed range: 1-255